"""one-desk against a real adapter run, not an illustration.

`products/data/adapter_runs.json` holds 48 variants generated by
`qwen2.5:14b-instruct` from 12 real source texts, via `scripts/run_adapter.py`.
The suite reads the cache and never calls a model.

Every figure asserted here was produced by running this code over that file.
"""

import statistics

import pytest

from onedesk.adapter import CACHE, PLATFORMS, load, measure
from onedesk.variants import ARCHIVE, baseline

pytestmark = pytest.mark.skipif(not CACHE.exists(), reason="no adapter run cached")


@pytest.fixture(scope="module")
def measured():
    return measure()


@pytest.fixture(scope="module")
def runs():
    return [r for r in load() if r.usable]


def test_the_run_is_real_and_recorded(measured, runs):
    assert measured.runs == 12
    assert measured.samples == 48
    assert measured.model == "qwen2.5:14b-instruct"
    assert all(set(r.variants) == set(PLATFORMS) for r in runs)


def test_each_variant_stays_close_to_its_source(measured):
    # Half the source's content words survive into each variant.
    assert measured.to_source_median == pytest.approx(0.528, abs=0.05)


def test_but_the_variants_genuinely_differ_from_each_other(measured):
    # THE CORRECTION. Four variants of one source overlap each other at 0.29,
    # against a human baseline of 0.23 for two people rendering the same
    # content independently. The adaptation is real, not cosmetic — which is
    # the opposite of what this product's README predicted.
    assert measured.cross_variant_median == pytest.approx(0.290, abs=0.05)


@pytest.mark.skipif(not ARCHIVE.exists(), reason="AMI corpus not on disk")
def test_the_variants_are_nearly_as_distinct_as_two_people(measured):
    human = baseline().same_median
    assert human == pytest.approx(0.229, abs=0.02)
    # Within a third of the human figure, not a multiple of it.
    assert abs(measured.cross_variant_median - human) < 0.10


@pytest.mark.skipif(not ARCHIVE.exists(), reason="AMI corpus not on disk")
def test_what_it_does_not_do_is_leave_the_source_behind(measured):
    # The real cost: each variant is ~2.3x closer to its source than an
    # independent rendering of the same content would be. It paraphrases where
    # a person re-conceives.
    human = baseline().same_median
    assert measured.versus(human) == pytest.approx(2.31, abs=0.4)
    assert measured.versus(human) > 1.8


def test_how_much_a_platform_transforms_varies_twofold(runs):
    medians = {p: statistics.median([r.overlaps[p] for r in runs]) for p in PLATFORMS}
    assert medians["instagram"] < medians["x"]
    assert medians["x"] / medians["instagram"] > 1.7
    # Instagram rewrites most, X least - the prompts differ and it shows.


def test_the_short_platform_is_the_least_transformed(runs):
    medians = {p: statistics.median([r.overlaps[p] for r in runs]) for p in PLATFORMS}
    assert max(medians, key=medians.get) == "x"


def test_an_empty_variant_is_not_counted():
    from onedesk.adapter import Run

    assert not Run(source="a source with plenty of content words here", variants={}).usable


def test_a_missing_run_is_reported_rather_than_faked():
    from onedesk.adapter import NoRunsError

    with pytest.raises(NoRunsError):
        load(str(CACHE.parent / "nope.json"))
